export { default as Slider } from './Slider';
export { Header } from './Header';
export { default as Department } from './Department';
export { default as Baner } from './Baner';
export { default as Quote } from './Quote';
export { default as LogInForm } from './LogInForm';
export { default as Teacher } from './Teacher';
export { default as Label } from './Label';
export { default as Links } from './Links';
export { default as Partners } from './Partners';
export { default as Copyright } from './Copyright';
export { default as BackgroundContainer } from './BackgroundContainer';
export { default as MobileMenu } from './MobileMenu';
export { default as Menu } from './Menu';
export { default as Map } from './Map';
export { default as Product } from './Product';
